### PR TITLE
Add Routing, Functional and SVG Features

### PR DESCRIPTION
**Pull request by bushmusi**
> # In this activity below features have been added

1. Add `sass-loader`
2. Add `header, Navbar and Menu Icon`
3. Deploy to **GitHub pages**
4. Add `404` page
5. Refactor code to functional and class components

> ## [Live Demo](https://bushmusi.github.io/react-todolist/)

### CODE REVIEW

**Comment by saied2035** [comment]
despicable-me-minions

- fulfilled the Requirements ✔️ 
- clear PR ✔️
- proffisional documentation ✔️ 
-  nice style ✔️ 

nothing more to say. it's time to merge 🥇

**Review by saied2035 — APPROVED** [review]
despicable-me-minions

- fulfilled the Requirements ✔️ 
- clear PR ✔️
- proffisional documentation ✔️ 
-  nice style ✔️ 

nothing more to say. it's time to merge 🥇

**Review by AmanuelAsfaw — APPROVED** [review]
# Status **Approved** 🟢 

- well documented
- professional commit
- [**Changes**] with one simple error at about page put the correct information please

**Comment by bushmusi** [comment]
> # Status **Approved** 🟢
> * well documented
> * professional commit
> * [**Changes**] with one simple error at about page put the correct information please

Noted and fixed @AmanuelAsfaw

**Pull request merged**
